pr comments

diff --git a/.github/workflows/setup-binary-test.yml b/.github/workflows/setup-binary-test.yml
--- a/.github/workflows/setup-binary-test.yml
+++ b/.github/workflows/setup-binary-test.yml
@@ -13,89 +13,42 @@
 # limitations under the License.
 
 name: 'setup-binary-test'
+
 on:
   pull_request:
     paths:
       - '.github/actions/setup-binary/**'
 jobs:
-  setup-binary-test-ubuntu:
+  setup-binary-test:
     strategy:
+      fail-fast: false
       matrix:
         os:
           - 'ubuntu-latest'
           - 'ubuntu-20.04'
-    runs-on: '${{ matrix.os }}'
-    steps:
-      - name: 'Checkout'
-        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
-
-      - name: 'Path'
-        id: 'path'
-        shell: 'bash'
-        run: |
-          echo "path=${HOME}/.abc" >> $GITHUB_OUTPUT
-
-      - name: 'Setup binary (no cache)'
-        uses: './.github/actions/setup-binary' # ratchet:exclude
-        with:
-          name: 'abc'
-          install_dir: '${{ steps.path.outputs.path }}'
-          download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_linux_amd64.tar.gz'
-
-      - name: 'Setup binary (cache)'
-        uses: './.github/actions/setup-binary' # ratchet:exclude
-        with:
-          name: 'abc'
-          install_dir: '${{ steps.path.outputs.path }}'
-          download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_linux_amd64.tar.gz'
-          enable_cache: true
-
-      - name: 'Test'
-        shell: 'bash'
-        run: 'abc --version'
-
-  setup-binary-test-windows:
-    strategy:
-      matrix:
-        os:
           - 'windows-latest'
           - 'windows-2019'
-    runs-on: '${{ matrix.os }}'
-    steps:
-      - name: 'Checkout'
-        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
-
-      - name: 'Path'
-        id: 'path'
-        shell: 'bash'
-        run: |
-          echo "path=${HOME}/.abc" >> $GITHUB_OUTPUT
-
-      - name: 'Setup binary (no cache)'
-        uses: './.github/actions/setup-binary' # ratchet:exclude
-        with:
-          name: 'abc'
-          install_dir: '${{ steps.path.outputs.path }}'
-          download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_windows_amd64.zip'
-
-      - name: 'Setup binary (cache)'
-        uses: './.github/actions/setup-binary' # ratchet:exclude
-        with:
-          name: 'abc'
-          install_dir: '${{ steps.path.outputs.path }}'
-          download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_windows_amd64.zip'
-          enable_cache: true
-
-      - name: 'Test'
-        shell: 'bash'
-        run: 'abc --version'
-
-  setup-binary-test-macos:
-    strategy:
-      matrix:
-        os:
           - 'macos-latest'
           - 'macos-11'
+        include:
+          - os: 'ubuntu-latest'
+            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_linux_amd64.tar.gz'
+
+          - os: 'ubuntu-20.04'
+            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_linux_amd64.tar.gz'
+
+          - os: 'windows-latest'
+            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_windows_amd64.zip'
+
+          - os: 'windows-2019'
+            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_windows_amd64.zip'
+
+          - os: 'macos-latest'
+            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_darwin_amd64.tar.gz'
+
+          - os: 'macos-11'
+            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_darwin_amd64.tar.gz'
+
     runs-on: '${{ matrix.os }}'
     steps:
       - name: 'Checkout'
@@ -107,21 +60,34 @@ jobs:
         run: |
           echo "path=${HOME}/.abc" >> $GITHUB_OUTPUT
 
-      - name: 'Setup binary (no cache)'
+      - name: 'Setup binary (save cache)'
         uses: './.github/actions/setup-binary' # ratchet:exclude
         with:
-          name: 'abc'
-          install_dir: '${{ steps.path.outputs.path }}'
-          download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_darwin_amd64.tar.gz'
+          install_path: '${{ steps.path.outputs.path }}'
+          download_url: '${{ matrix.download_url }}'
+          cache_key: '${{ runner.name }}_abc_${{ github.sha }}'
 
-      - name: 'Setup binary (cache)'
+      - name: 'Setup binary (restore cache)'
         uses: './.github/actions/setup-binary' # ratchet:exclude
         with:
-          name: 'abc'
-          install_dir: '${{ steps.path.outputs.path }}'
-          download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_darwin_amd64.tar.gz'
-          enable_cache: true
+          install_path: '${{ steps.path.outputs.path }}'
+          download_url: '${{ matrix.download_url }}'
+          cache_key: '${{ runner.name }}_abc_${{ github.sha }}'
+
+      - name: 'Add binary to path'
+        shell: 'bash'
+        env:
+          BINARY_PATH: '${{ steps.path.outputs.path }}'
+        run: |-
+          echo "${BINARY_PATH}" >> $GITHUB_PATH
 
       - name: 'Test'
         shell: 'bash'
-        run: 'abc --version'
+        run: |
+          GOT=$(abc -version 2>&1) # abcxyz/pkg/cli writes help to stderr
+          WANT="abc 0.0.1-alpha4"
+
+          if [[ "${GOT}" != "${WANT}"* ]]; then
+            echo "::error ::Expected ${GOT} to be ${WANT}"
+            exit 1
+          fi
